console.log('begin');
console.log('fetures added');
console.log('all good');
console.log('beta version done');
console.log('new features');
console.log('ajalas esta bien perro');
console.log('soy la mera pistola');
console.log('ya acabe');
console.log('vamos a agregar mas cositas');
console.log('taggeando emn develop');
console.log('para ver que pasa');